---
kind: pipeline
name: node19
clone:
  disable: false
steps:
  - name: test
    image: node:19.6.0-alpine
    commands:
      - make install
      - make test

---
kind: pipeline
name: node18
clone:
  disable: false
steps:
  - name: test
    image: node:18.14.0-alpine
    commands:
      - make install
      - make test

---
kind: pipeline
name: node16
clone:
  disable: false
steps:
  - name: test
    image: node:16.19.0-alpine
    commands:
      - make install
      - make test

---
kind: pipeline
name: node14
clone:
  disable: false
steps:
  - name: test
    image: node:14.21.2-alpine
    commands:
      - make install
      - make test
