---
kind: pipeline
name: node20
clone:
  disable: false
steps:
  - name: test
    image: node:20.4.0-alpine
    commands:
      - make install
      - make test

---
kind: pipeline
name: node18
clone:
  disable: false
steps:
  - name: test
    image: node:18.16.1-alpine
    commands:
      - make install
      - make test

---
kind: pipeline
name: node16
clone:
  disable: false
steps:
  - name: test
    image: node:16.20.1-alpine
    commands:
      - make install
      - make test

---
kind: pipeline
name: node14
clone:
  disable: false
steps:
  - name: test
    image: node:14.21.3-alpine
    commands:
      - make install
      - make test
