---
kind: pipeline
name: node22
clone:
  disable: false
steps:
  - name: test
    image: node:22.4.1-alpine3.20
    commands:
      - make install
      - make test

---
kind: pipeline
name: node20
clone:
  disable: false
steps:
  - name: test
    image: node:20.15.1-alpine3.20
    commands:
      - make install
      - make test
